### ISSUE TITLE
Handle duplicate shoot/seed conditions

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener-metrics-exporter#35]
**What happened**:
If a shoot or seed has duplicate conditions, the gardener-metrics-exporter will error and not expose any metrics.
For example if a shoot has the following status the gme will not be able to expose any metrics.
```
status:
  conditions:
  - lastTransitionTime: "2020-08-06T04:09:26Z"
    lastUpdateTime: "2020-08-06T08:56:29Z"
    message: API server /healthz endpoint responded with success status code. [response_time:2ms]
    reason: HealthzRequestSucceeded
    status: "True"
    type: APIServerAvailable
  - lastTransitionTime: "2020-08-06T04:09:26Z"
    lastUpdateTime: "2020-08-06T08:56:29Z"
    message: All control plane components are healthy.
    reason: ControlPlaneRunning
    status: "True"
    type: ControlPlaneHealthy
  - lastTransitionTime: "2020-08-06T04:09:26Z"
    lastUpdateTime: "2020-08-06T08:56:29Z"
    message: Every node registered to the cluster is ready.
    reason: EveryNodeReady
    status: "True"
    type: EveryNodeReady
  - lastTransitionTime: "2020-08-06T06:55:55Z"
    lastUpdateTime: "2020-08-06T08:56:29Z"
    message: All system components are healthy.
    reason: SystemComponentsRunning
    status: "True"
    type: SystemComponentsHealthy
  - lastTransitionTime: "2020-08-05T14:13:10Z"
    lastUpdateTime: "2020-08-05T14:13:10Z"
    message: Gardenlet is posting ready status.
    reason: GardenletReady
    status: "True"
    type: GardenletReady
  - lastTransitionTime: null
    lastUpdateTime: null
    message: ""
    reason: ""
    status: ""
    type: ""
  - lastTransitionTime: null
    lastUpdateTime: null
    message: ""
    reason: ""
    status: ""
    type: ""
```

In the example above there are two duplicate conditions that contain no data.
**What you expected to happen**:
Regardless of how duplicate conditions got there, the gme should be able to handle this without having an error. It could skip this metric and log an error instead of not exposing metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Add two duplicate conditions to a shoot/seed.
